### ISSUE TITLE
form is missing in Advanced-Wireless.php

### ISSUE THREAD

**Issue by dex2000** [ronnyvdbr/ronnyvdbr.github.io#11]
in the advanced wireless options its not possible to change anything, because there is no form

**Comment by ronnyvdbr** [comment]
You are right, that part is not completed yet.
Op 23-okt.-2015 21:56 schreef "MKnight" notifications@github.com:

**Comment by ronnyvdbr** [comment]
Hi, this page was taken off-line for further development.
It will be implemented again if it is finished and working.
