### ISSUE TITLE
install not logging in

### ISSUE THREAD

**Issue by parapac** [ronnyvdbr/ronnyvdbr.github.io#15]
Hi
This is a great idea, love the idea of having a UI to be able to work with BUT....
I have installed on a B+ Raspi.
I get the login page on IPaddress/login.php.
But when I do login the page that opens is a grey page.
looking in the var/www folder everything seems to be there.

**Comment by ronnyvdbr** [comment]
Hi, this problem is now resolved in version 1.5.
