### ISSUE TITLE
Waiting for sd card (settings partition)

### ISSUE THREAD

**Issue by dipankardrc** [ronnyvdbr/ronnyvdbr.github.io#16]
After creating partition on sd card using fdisk and rebooting, the raspbian is stuck on the start screen which shows "For Recovery mode, hold shift". And a window shows "Waiting for sd card (settings partition)". What to do?

**Comment by ronnyvdbr** [comment]
make sure you have selected the correct partition.
A raspbian SD card is divided into 2 partitions, the boot partition and the working partition.
It sounds like you killed your boot partition, make sure to select the other one.

**Comment by dipankardrc** [comment]
which one is the boot partition?

**Comment by ronnyvdbr** [comment]
If you startend with the raspbian foundation image and if u have written that to sd card then your first partition Will be your boot partition.

Verstuurd vanaf mijn iPad

**Comment by ronnyvdbr** [comment]
Closed due to no further comments.
