### ISSUE TITLE
Changing DNS?

### ISSUE THREAD

**Issue by ianwesty** [ronnyvdbr/ronnyvdbr.github.io#19]
Hi, 

Thanks for your efforts with this project.

The main reason I tried this project was so that I could add my own DNS servers. I've tried adding the following, but nothing has worked both in router and AP mode.

Adding `prepend domain-name-servers x.x.x.x` in /etc/dhcp/dhclient.conf 

Adding `dns-nameservers x.x.x.x` in /etc/network/interfaces

Adding `namserver=x.x.x.x` in /etc/resolv.conf

Cheers,
Ian

**Comment by ronnyvdbr** [comment]
Hi, a new version was released where this functionality should be working.
Please give it a try and let me know if you get any further trouble.
