### ISSUE TITLE
Address For Web UI

### ISSUE THREAD

**Issue by olud22** [ronnyvdbr/ronnyvdbr.github.io#21]
Hi, i have gotten the Raspberry PI Wifi Router up and running and connected two devices. I have been trying to access the web ui of the router but i don't know what the address is. What is it please?

**Comment by ronnyvdbr** [comment]
Hi, you can find the default settings of the router at
https://github.com/ronnyvdbr/ronnyvdbr.github.io/blob/master/defconfig/routersettings.ini
Op 2 apr. 2016 00:49 schreef "olud22" notifications@github.com:

**Comment by olud22** [comment]
Thanks for your reply. I was under the impression that the picture below existed. How do i get to that?
![screenshot](https://cloud.githubusercontent.com/assets/9630834/14225889/8b606e00-f898-11e5-9aee-2687ecade334.PNG)

**Comment by ronnyvdbr** [comment]
Well, once u know the ip address you enter this in the address bar of your
browser, then u log into the router with username and password.
Op 2 apr. 2016 13:03 schreef "olud22" notifications@github.com:

**Comment by olud22** [comment]
sorry for the dumb questions. Okay here is my Dilemma:
On the Raspberry pi, i can to  localhost on the raspberry pi browser and check the raspberry pi wifi router web gui. However, since i want to make my Raspberry pi wifi router headless, i want to be able to get to the web gui from my Laptop that is connected to the Raspberry pi Wifi router. I have localhost but it didn't work, i have tried 192.168.1.0,192.168.1.1,192.168.1.254 but none of them is working. So my question is how do i get to the web gui from my connected devices e.g Laptop

**Comment by olud22** [comment]
Thanks a lot. I figured it out. Again, really cool project
