### ISSUE TITLE
Captive Portal is unstable

### ISSUE THREAD

**Issue by sadtearz** [ronnyvdbr/ronnyvdbr.github.io#4]
Great job sir. I just have an issue  on activating captive portal. It is not working in my next reboot.
And if possible can you please include support to usb LAN adapter additional to usb wireless lan  to broadcast in local network? and also please add login form before continuing to web configuration portal. God bless

**Comment by ronnyvdbr** [comment]
Hi, the problem with the captive portal not working across reboots is fixed, the latest release is downloadable from https://ronnyvdbr.github.io
If u are willing to sponsor a usb lan adapter then I will work out an extra feature for it.

**Comment by sadtearz** [comment]
hi. very impressive sir. i will try it asap. thank you
