### ISSUE TITLE
Feature Request: Wireless client and software AP with a single Wi-Fi device

### ISSUE THREAD

**Issue by roiz-git** [ronnyvdbr/ronnyvdbr.github.io#5]
this would be AWSOME - taking a raspi device to any place (especially hotels) and allow it to function as secured-private_nat_provider repeater
This way, you will have good wifi connection at any place in the room AND you will be secured behind firewall and iptables etc.
NAT option will allow several devices to connect securely via netwrok w/o evil forces eavesdropping on you

Along w/ your roadmap, it seems that this feature request has a very little effort as shown in the embedded (arch linux) wiki 
https://wiki.archlinux.org/index.php/Software_access_point#Wireless_client_and_software_AP_with_a_single_Wi-Fi_device

**Comment by ronnyvdbr** [comment]
Hi, I believe this feature is already available.
It is called router mode, check the web gui and switch the operation mode to router mode.
