### ISSUE TITLE
WPA password change does not work

### ISSUE THREAD

**Issue by roiz-git** [ronnyvdbr/ronnyvdbr.github.io#6]
I changed the wpa password via the web interface and failed to connect so I sshed into the hostapd.conf and noticed the default password was not changed. When I modified the file manually everything worked fine!

keep up the great work!

**Comment by dex2000** [comment]
Vote/ Confirmed

**Comment by dex2000** [comment]
Is there any work on it?

**Comment by ronnyvdbr** [comment]
Hi, this problem is resolved now in version 1.5.1
