### ISSUE TITLE
Default username/password for web ui not working

### ISSUE THREAD

**Issue by TimDowker** [ronnyvdbr/ronnyvdbr.github.io#9]
I have tried the default username/password combo of admin/raspberry to login to the web ui but it doesn't work.

Any thoughts?

**Comment by ronnyvdbr** [comment]
Hi, yes I think it's a bug, still need to test it though.
Connect your network cable before U power up your Raspberry Pi.

**Comment by Sutured** [comment]
I also am having this issue to no avail. Ugh.

Is there a way to circumvent this? I am so excited to use it and I haven't found a way to cut it out so that I can get in. I've tried it with everything attached.

**Comment by ronnyvdbr** [comment]
Hi, please note that the problems with the passwords are now resolved.
Version 1.5.1 which is ported to Raspbian Jessie now resolves this.

**Comment by polzy** [comment]
Good :) 

It's possible to change the password with ssh on raspberry pi  ?

**Comment by ronnyvdbr** [comment]
hi which version of the image are you using or did u build one yourself?
Op 4 mei 2016 11:39 a.m. schreef "polzy" notifications@github.com:

**Comment by polzy** [comment]
I don't know... I have build on 2015 december and I don't have phisical access on my raspberry pi :(

**Comment by ronnyvdbr** [comment]
u will need to start your mysql server.
probably its not running, hence the password database is not available.
sudo service mysql start
Op 4 mei 2016 12:17 schreef "polzy" notifications@github.com:
